version: '3.8'

services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo-production
    ports:
      - "${MCPO_PORT:-8000}:8000"
    volumes:
      - ../config:/app/config:ro
      - ../env/.env.production:/app/.env:ro
      - mcpo-data:/app/data
      - sandbox:/app/sandbox
    command: >
      mcpo --host 0.0.0.0 --port 8000 
      --api-key "${API_KEY}" 
      --config /app/config/production.json
      --env-path /app/.env
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app/servers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Redis for session management (if needed by MCP servers)
  redis:
    image: redis:7-alpine
    container_name: mcpo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-changeme}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Nginx reverse proxy for HTTPS termination
  nginx:
    image: nginx:alpine
    container_name: mcpo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/ssl:ro
    depends_on:
      mcpo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mcpo-data:
    driver: local
  redis-data:
    driver: local
  sandbox:
    driver: local

networks:
  default:
    name: mcpo-production
    driver: bridge